config/routes.rb
Rails.application.routes.draw do
  resources :moviers do
      resources :comments 
  end
  devise_for :users

  root "moviers#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :moviers
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :movier, optional: true
  belongs_to :user, optional: true
end

app/models/movier.rb
class Movier < ApplicationRecord
   mount_uploader :movierimage, MovierimageUploader
   has_many :comments, dependent: :destroy
   belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :moviers
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @movier = Movier.find(params[:movier_id])
    @comment = @movier.comments.create(params[:comment].permit(:body))
    @comment.save
    if
      @comment.save
      redirect_to movier_path(@movier)
    else
      render 'new'
    end
  end
  def edit
    @movier = Movier.find(params[:movier_id])
    @comment = @movier.comments.find(params[:id])
  end

  def update
    @movier = Movier.find(params[:movier_id])
    @comment = @movier.comments.find(params[:id])

    if @comment.update(params[:comment].permit(:comment))
      redirect_to movier_path(@movier)
    else
      render 'edit'
    end
  end
  def destroy
    @movier = Movier.find(params[:movier_id])
    @comment = @movier.comments.find(params[:id])
    @comment.destroy
    redirect_to movier_path(@movier)
  end
end

app/controllers/moviers_controller.rb
class MoviersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movier, only: [:show, :edit, :update, :destroy]

  # GET /moviers
  # GET /moviers.json
  def index
    @moviers = Movier.all.order("created_at DESC")
  end

  # GET /moviers/1
  # GET /moviers/1.json
  def show
  end

  # GET /moviers/new
  def new
    @movier = current_user.moviers.build
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  # GET /moviers/1/edit
  def edit
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  # POST /moviers
  # POST /moviers.json
  def create
    @movier = current_user.moviers.build(movier_params)
    @movier.category_id = params[:category_id]
    respond_to do |format|
      if @movier.save
        format.html { redirect_to @movier, notice: 'Movier was successfully created.' }
        format.json { render :show, status: :created, location: @movier }
      else
        format.html { render :new }
        format.json { render json: @movier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moviers/1
  # PATCH/PUT /moviers/1.json
  def update
    respond_to do |format|
      if @movier.update(movier_params)
        format.html { redirect_to @movier, notice: 'Movier was successfully updated.' }
        format.json { render :show, status: :ok, location: @movier }
      else
        format.html { render :edit }
        format.json { render json: @movier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moviers/1
  # DELETE /moviers/1.json
  def destroy
    @movier.destroy
    respond_to do |format|
      format.html { redirect_to moviers_url, notice: 'Movier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movier
      @movier = Movier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movier_params
      params.require(:movier).permit(:category_id, :title, :description, :year, :director, :actors, :movierimage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/moviers_helper.rb
module MoviersHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= comment.body %>
        <%= time_ago_in_words(comment.created_at) %> ago

        <%= link_to "edit", edit_movier_comment_path(comment.movier, comment) %>
        <%= link_to "delete ", [comment.movier, comment], method: :delete, data: { confirm: "Are you sure?"} %>

      </div>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@movier, @movier.comments.build]) do |f| %>
  <%= f.text_area :body, class: "form-control", rows: '5', required: true %>
  <br>
  <%= f.submit class: "btn btn-outline-success" %>
<% end %>

app/views/comments/edit.html.erb
<div class="comment clearfix space">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

<h3>Edit Comments</h3>
<%= form_for([@movier, @comment]) do |form| %>
  <%= form.text_area :body, class: "form-control", rows: 5, requered: true %>
  <%= form.submit class: "btn btn-outline-success" %>

<% end %>
</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blognested</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar navbar-light fixed-top" style="background-color: #e3f2fd;">
      <%= link_to "MovieNow", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link"  %>
          </li>
          <li class="nav-item">
          <%= link_to 'New Movier', new_movier_path, class: "nav-link" %>
          </li>
        <% else %>
        <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path , class: "nav-link"%>
          </li>
        <li class="nav-item">
        <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>

      </li>
      <% Category.all.each do |category| %>
        <li class="<%= 'active'%>">
          <%= link_to category.name, moviers_path(category: category.name), class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          My Profile
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

    <%= yield %>
  </body>
</html>

app/views/moviers/_form.html.erb
<%= form_with(model: movier, local: true ) do |form| %>
  <% if movier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movier.errors.count, "error") %> prohibited this movier from being saved:</h2>

      <ul>
      <% movier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
  <%= form.file_field :movierimage %>
  </div>
  <div class="field">
    <%= select_tag(:category_id, options_for_select(@categories), prompt: "Choose movie category" ) %>
  </div>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :movier_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :movier_description %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.date_select :year, id: :movier_year %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.text_field :director, id: :movier_director %>
  </div>

  <div class="field">
    <%= form.label :actors %>
    <%= form.text_area :actors, id: :movier_actors %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/moviers/edit.html.erb
<h1>Editing Movier</h1>


<%= form_with(model: @movier, local: true ) do |form| %>
    <%= form.file_field :movierimage %> <br>
    <%= form.select  :category_id, @categories %> <br>
    <%= form.text_field :title, id: :movier_title %> <br>
    <%= form.text_area :description, id: :movier_description %> <br>
    <%= form.date_select :year, id: :movier_year %> <br>
    <%= form.text_field :director, id: :movier_director %> <br>
    <%= form.text_area :actors, id: :movier_actors %><br>

    <%= form.submit %>

<% end %>


<%= link_to 'Show', @movier %> |
<%= link_to 'Back', moviers_path %>

app/views/moviers/index.html.erb
<div class="space allmovie">
  <div class="container">
    <div class="row">


    <% @moviers.each do |movier| %>
    <div class="col-md-3">
      <div class="card">
        <div class="image-top">
        <%= image_tag  movier.movierimage_url  if  movier.movierimage? %>
        </div>
        <div class="card-body">
          <a  class=" " data-toggle="collapse" href="#movier-<%= movier.id %>" role="button" aria-expanded="false" aria-controls="collapseExample">
            <p>
              <strong>Title:</strong>
            <%=   movier.title   %>
          </p>
          </a>


<div class="collapse" id="movier-<%= movier.id %>">
  <div class="  card-body">
    <p>
      <strong>Description:</strong>
       <%=truncate(movier.description, length: 50) %>
     </p>
     <p>
       <strong>Year:</strong>
       <%= movier.year %>
     </p>

      <p > Category:  <strong class="badge badge-secondary"><%=  movier.category.name if movier.category  %></strong></p>

     <p>
       <strong>Director:</strong>
       <%= movier.director %>
     </p>
     <p>
       <strong>Actors:</strong>
       <%= movier.actors %>
     </p>
      <p>
       <strong> Post created:</strong>
       <span   class="badge badge-secondary" >

       <%= time_ago_in_words(movier.created_at) %> ago </span>
     </p>
     <p><%= link_to "Read more...", movier %>  </p>

  </div>
</div>
         </div>
       </div>
       </div>
    <% end %>
  </div>
</div>
</div>

app/views/moviers/new.html.erb
<h1>New Movier</h1>

<%= render 'form', movier: @movier %>

<%= link_to 'Back', moviers_path %>

app/views/moviers/show.html.erb
<div class="space allmovie">
  <div class="container">
    <div class="row">
      <div class="col-md-8  mx-auto">
        <div class="card">
          <div class="card-body">


 <%= image_tag (@movier.movierimage_url) if @movier.movierimage? %>
<p>
  <strong>Title:</strong>
  <%= @movier.title %>
</p>
<p > Category:  <strong class="badge badge-secondary"><%=  @movier.category.name if @movier.category  %></strong></p>

<p>
  <strong>Description:</strong>
  <%= @movier.description %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movier.year %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movier.director %>
</p>

<p>
  <strong>Actors:</strong>
  <%= @movier.actors %>
</p>
<%= link_to 'Edit', edit_movier_path(@movier),class: "btn btn-outline-success" %>
 <%= link_to 'Destroy', @movier, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-outline-danger" %>
<%= link_to 'Back', moviers_path, class: "btn btn-outline-secondary" %>


  <div class="comments">
    <p><%= @movier.comments.count %> comments</p>
    <%= render @movier.comments %>
    <%= render "comments/form" %>
  </div>

</div>
</div>
</div>
</div>
</div>
</div>